-- Highlight on yank
-- vim.api.nvim_create_autocmd("TextYankPost", {
-- 	group = vim.api.nvim_create_augroup("highlight_yank", { clear = true }),
-- 	pattern = "*",
-- 	desc = "Highlight selection on yank",
-- 	callback = function()
-- 		vim.highlight.on_yank({ timeout = 200, visual = true })
-- 	end,
-- })

-- TODO: maybe put this back in for code
-- vim.api.nvim_create_autocmd("VimResized", {
-- 	group = vim.api.nvim_create_augroup("WinResize", { clear = true }),
-- 	pattern = "*",
-- 	command = "wincmd =",
-- 	desc = "Auto-resize windows on terminal buffer resize.",
-- })
